apiVersion: v1
kind: Service
metadata:
  labels:
    app: smtp2slack
  name: smtp2slack-smtp
  namespace: smtp2slack
spec:
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 2525
  selector:
    app: smtp2slack
  type: LoadBalancer
